name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: use this action, test solution dir
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: CS5800Proj.Testing
          report_name: tests
          report_title: Test Results
          github_token: ${{ secrets.GITHUB_TOKEN }}
